services:
  satisfactory-server:
    container_name: satisfactory-server
    hostname: satisfactory-server
    build: .
    ports:
      - 7777:7777/udp
      - 7777:7777/tcp
    volumes:
      - truenas-satisfactory:/config
    environment:
      - MAXPLAYERS=5
      - PGID=1000
      - PUID=1000
      - ROOTLESS=false
      - STEAMBETA=false
    restart: unless-stopped
    pull_policy: build
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 4G

volumes:
  truenas-satisfactory:
    external: true
